name = "spinmacho-app-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmacho-app.de"
HMAC_KEY = "7230a9813016674799ae5deba0e2c695a62a0b8377ff1938b8626f3f2ba84551"
COOKIE_NAME = "q4o"
PLAY_PATH = "try"
BUTTON_ID = "pcc49fef3457599b1bb63c3a5b14dbd34"
GATE_SALT = "306e94264ad5a9f2"
