name = "spinmacho-app-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmacho-app.de"
HMAC_KEY = "7230a9813016674799ae5deba0e2c695a62a0b8377ff1938b8626f3f2ba84551"
COOKIE_NAME = "rmp"
PLAY_PATH = "explore"
BUTTON_ID = "pcc49fef3457599b1bb63c3a5b14dbd34"
GATE_SALT = "ed949416d9e17f5d"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "vs34"
CTA_SELECTOR = ".play-button"
